Make the code more idiomatic with regards to parallelisation
Instead of storing result data in a global map which can lead to "fatal
error: concurrent map writes", pass the data around with channels.

"Don't communicate by sharing memory, share memory by communicating".

Resolves: https://github.com/dxw/git-test-branch/issues/18